### ISSUE TITLE
Check for fake proxies

### ISSUE THREAD

**Issue by smokenmirrors2** [openproxyspace/unfx-proxy-checker#1]
When checking public lists ive been coming along alot of fake proxies with coin miner scripts running on it. If you could like make it check a website and verify the contents of it the page, then you could get rid of them.

**Comment by assnctr** [comment]
Proxy verify by 'Validate string' in Judges settings. I will make dangerous proxy detect in next update.

**Comment by assnctr** [comment]
Proxy verify by "Validate string" in Judges settings. I will make dangerous proxy detection in next update.

**Comment by smokenmirrors2** [comment]
Your download locations are messed up btw, http://localhost:3000/download/unfx-proxy-checker-v1.0.3-win32-x64.rar

**Comment by relloccate** [comment]
Will be added in v1.0.4

**Comment by smokenmirrors2** [comment]
Damn bro, close and reopen this enough times lol
