### ISSUE TITLE
save config on 1.5

### ISSUE THREAD

**Issue by rchunter80** [openproxyspace/unfx-proxy-checker#13]
Hi , sorry i have add much url judges like 200 url , too much time but i can't save this , after done checked a small list for test , reopen checker will be loaded on default setting back . Please update save and restore setting , thanks bro

**Comment by relloccate** [comment]
Run with administrator privileges.

**Comment by relloccate** [comment]
Fixed this issue, patch v1.5.2. Thanks for the issue.
