### ISSUE TITLE
Debian java help?

### ISSUE THREAD

**Issue by usaflees** [openproxyspace/unfx-proxy-checker#14]
Hello sir, thanks for an awesome program, I am trying to run this on debian\linux on Parrot OS.  any advice?  I am getting errors every which way i am trying.  thanks

**Comment by relloccate** [comment]
Hi, thanks for the issue. I just don't know, don't have other OS, only Win. I will try to build application for all platforms, may be on next week. I have no idea how i can help you, sorry.

**Comment by usaflees** [comment]
thanks for the quick reply. I didnt see the notification.  So I have been working on this and I found some things you could possibly edit in the build of the portable application.  When using Wine to run it these errors pop.  

002f:err:module:import_dll Loading library Secur32.dll (which is needed by L"C:\\users\\mike\\Temp\\nsh2331.tmp\\app\\Unfx Proxy Checker.exe") failed (error c000007b).
002f:err:module:attach_dlls Importing dlls for L"C:\\users\\mike\\Temp\\nsh2331.tmp\\app\\Unfx Proxy Checker.exe" failed, status c0000135

its basically trying to use dll's but I do not know the package they are included in if not secur32

Which packager did you use? Nuget?

is the source files for the portable version anywhere accessible here?  I would like to help get this working!

**Comment by relloccate** [comment]
Idk, app builds through https://github.com/electron-userland/electron-builder.

**Comment by usaflees** [comment]
What could be awesome is if you could select a .deb package to be built?  Could you try? It says it’s available automatically

**Comment by usaflees** [comment]
Hey brother, trying to give this another shot since ive got a bit of time.  Are you using yarn or npm to compile?

would it be possible to run yarn dist .deb?

**Comment by relloccate** [comment]
I have only win, on win packages builds only for win. Remote builder is not available.
Dude, compile by yourself.

Fork
npm install
npm run package with. deb flag.

**Comment by usaflees** [comment]
I will ty that, thanks for the idea! I’m new to the Compiling thing as a whole, much appreciated! 

Edit:  quick question but, how is the command different if you wanted to make it “portable” or not on windows?
