### ISSUE TITLE
i have problem with 150 judges

### ISSUE THREAD

**Issue by rchunter80** [openproxyspace/unfx-proxy-checker#15]
hi , 

first thanks for ur app , it look like good more than old version , too fast . So i have a problem with multi judges like 130-150 url , it always stop and bland page , 1 of 3 process is die , open start 3 process but after error i seen 1 stoped maybe on checking judges step process . 

Thanks u again and have a nice day to u .

**Comment by relloccate** [comment]
For fix this issue i need your config. Can you send in tlg?

**Comment by rchunter80** [comment]
noproblem bro i will send my config to u , but sorry i don't have tlg now , can i send to u by another ? exam ur email bla bla or here , thanks bro

**Comment by relloccate** [comment]
Maybe facebook pm?
https://www.facebook.com/openproxyspace/

**Comment by relloccate** [comment]
Wait for update.

**Comment by rchunter80** [comment]
yes tks bro , i hope this project will be good more , grabber proxy is not
good too waiting for next update , regex grab and render list have a
problem .

**Comment by relloccate** [comment]
I work now with Open Proxy Space project, idk when i will work with other projects.

**Comment by loveyoursupport** [comment]
Just wondering that where to get URLs for more Judges :-(
btw excellent tool , thanks dev

**Comment by rchunter80** [comment]
i will get back my list and share tfor u , tks for ur work hard . sorry
along time am not check on my email and miss ur email that why slow reply
