### ISSUE TITLE
Why can you check socks only against HTTP websites ??

### ISSUE THREAD

**Issue by ruz0ne** [openproxyspace/unfx-proxy-checker#25]
hey i just want to know why this proxy checker can only check socks4, socks5 against http websites and not https?

for example i put in judge https://www.google.com/ tick SSL and tick VALIDATE with <title>Google
i go to core tab and tick only  HTTPS, Socks4 and Socks5 but when i press the check button i get

Error: you have no judges for HTTP/Socks4/Socks5

can you please add in next version to check socks4 and socks5 with https websites ?

thank you !

**Comment by relloccate** [comment]
Is already was added, wait for update.

**Comment by relloccate** [comment]
Fixed.
