### ISSUE TITLE
Only displaying 9999 Proxies

### ISSUE THREAD

**Issue by profpandaa** [openproxyspace/unfx-proxy-checker#26]
Hey, I'm trying to load about 15k proxies, but while checking the checker is only displaying 9999, is that just a limit on the label, or is the checker unable to check more than 9999 proxies?

**Comment by relloccate** [comment]
> Hey, I'm trying to load about 15k proxies, but while checking the checker is only displaying 9999, is that just a limit on the label, or is the checker unable to check more than 9999 proxies?

No, checker can check more than 9999. May be other proxies it's duplicates?
And you check only one proxy list before create the issue? Try more.

**Comment by profpandaa** [comment]
"And you check only one proxy list before create the issue? Try more." I tried about 10-15 proxy lists

**Comment by relloccate** [comment]
I need more info, because only you have this issue. On my computer all it's ok.

**Comment by profpandaa** [comment]
Will test it a bit more, maybe there were actually many duplicates.

**Comment by profpandaa** [comment]
Well, seems like it actually caused by duplicates. I just thought that it is kinda strange, that there are ALWAYS 9999 proxies. Sorry for wasting your time.
