### ISSUE TITLE
Can't delete judge when judge URL is too long

### ISSUE THREAD

**Issue by patrickdappollonio** [openproxyspace/unfx-proxy-checker#27]
Hello,

Amazing piece of software! I was working on some proxies when I noticed if the URL in the judges list is too long, the X to delete it is below the text, and it can't be clicked (since clicking in the URL enables or disables the judge) so you can just toggle that but not delete the judge anymore.

With that, if the URL list is too long, it ends up creating a big big list of disabled judges that you can't delete due to the X button being below the URL.

Any ideas on a workaround in the meantime?

**Comment by relloccate** [comment]
@patrickdappollonio Hi, sorry, this project is holded right now.
Check the config, and delete by 💪

- Save config path moved to '\Users\username\AppData\Roaming\unfx-proxy-checker'.
- For portable version path is current directory where application is running.

**Comment by relloccate** [comment]
Anyway, thanks for the issue, i know this bug, but i forgot to fix 🐌

**Comment by relloccate** [comment]
Fixed.
