### ISSUE TITLE
Proxy Filter

### ISSUE THREAD

**Issue by zHadsaw** [openproxyspace/unfx-proxy-checker#43]
You can add the "proxy filter" (https://openproxy.space/filter) in this proxy checker? or in another external program?

**Comment by relloccate** [comment]
Why you can't use this, due to LAG on input? I can add feature 'adding from file' without browser render, to avoid this.

**Comment by zHadsaw** [comment]
It would be a good idea, but i don't know if the people would go put the same .txt that are "ip:port"
with the proxy that are full of text. Therefore i vote in the option of be an extra button inside of 
program or a external program.
