### ISSUE TITLE
Feature supports checking all IP:PORT:USER:PASS types

### ISSUE THREAD

**Issue by SpearRipper** [openproxyspace/unfx-proxy-checker#44]
**Is your feature request related to a problem? Please describe.**
- some sites like Luminati.io and Webshare.io and others provide their proxies as IP:PORT:USER:PASSWORD
- or Domain:PORT:USER:PASSWORD, and when trying checking them it's working.

**Describe the solution you'd like**
- We do love to see feature supports checking all types of IP:PORT:USER:PASSWORD, and we will be so grateful.

**Describe alternatives you've considered**
Not sure of any.

**Additional context**
None.

**Comment by kolet** [comment]
6month after no answer , perhaps this project is dead ?

**Comment by relloccate** [comment]
@SpearRipper @kolet 
Added.
