### ISSUE TITLE
Linux release

### ISSUE THREAD

**Issue by plumped** [openproxyspace/unfx-proxy-checker#48]
Good day, 

is any Linux release planned or possible to build?

**Comment by BlitDev** [comment]
I also needed this software, when will the Linux release be?

**Comment by chromer030** [comment]
+1 for Linux build

**Comment by relloccate** [comment]
@chromer030 @plumped @BlitDev 

Tried to make a build today, it failed on WSL.
I will try later with docker or will install linux.
Anyway, it's coming soon.

**Comment by relloccate** [comment]
Done. v1.7.2.
