### ISSUE TITLE
Software does not continue to run at proxy check

### ISSUE THREAD

**Issue by tungtrinh1402** [openproxyspace/unfx-proxy-checker#49]
Software does not continue to run at proxy check
I can still press STOP
version: 1.7.0
![image](https://user-images.githubusercontent.com/79980599/190732634-fd973537-f3a5-469a-bcb4-e173a63c706a.png)

**Comment by relloccate** [comment]
@tungtrinh1402 

Thank you.
I don't understand why this happens, when developing everything is fine, the framework behaves differently.
I deleted the release, download the previous version, will look for what the problem.

**Comment by tungtrinh1402** [comment]
> @tungtrinh1402
> 
> Thank you. I don't understand why this happens, when developing everything is fine, the framework behaves differently. I deleted the release, download the previous version, will look for what the problem.

The 1.7.1 update works fine.
Using your own proxy is an effective combination https://openproxy.space/dashboard/proxy-list . I've been waiting for your update since 2019
![image](https://user-images.githubusercontent.com/79980599/190851918-a6c98255-47c8-48cd-9b8e-4843638be1b1.png)

**Comment by tungtrinh1402** [comment]
> @tungtrinh1402
> 
> Thank you. I don't understand why this happens, when developing everything is fine, the framework behaves differently. I deleted the release, download the previous version, will look for what the problem.

You can add share proxy live feature with personal account api + share directly to openproxy's public ip source for me to personally use or share for everyone to buy your Purchase key. it will create a big ip community for you.

**Comment by relloccate** [comment]
> > @tungtrinh1402
> > I've been waiting for your update since 2019

appreciate it =))))))))

**Comment by relloccate** [comment]
You can share the API key, then the user can select options in the builder (https://openproxy.space/api - Builder Page)
