### ISSUE TITLE
Req.

### ISSUE THREAD

**Issue by afwn90cj93201nixr2e1re** [openproxyspace/unfx-proxy-checker#5]
Добавить кнопку снятия всех фильтров(не удобно вручную все это тыкать), добавить фильтр по задержке('скорости')(delay).
![image](https://user-images.githubusercontent.com/9306996/48306789-03004700-e559-11e8-8cbb-e15b8c13e866.png)

Зачем нужен timeout - не понятно особо, выставили в 1100 в итоговом листе прокси с 2-12к задержкой.

**Comment by relloccate** [comment]
В следующем патче сделаю.
